### ISSUE TITLE
forget to ignore .settings, etc

### ISSUE THREAD

**Issue by wit543** [kwanwantku/arrayiterator#1]
You don't need to commit eclipse setting to your git. 
[.setting](https://github.com/kwanwantku/arrayiterator/tree/master/.settings)
[.classpath](https://github.com/kwanwantku/arrayiterator/blob/master/.classpath)
[.project](https://github.com/kwanwantku/arrayiterator/blob/master/.project)

**Comment by kwanwantku** [comment]
I fixed it already
